# Build Stage
FROM gradle:8.1.1-jdk17 AS builder
WORKDIR /app
COPY . .
RUN ./gradlew build --no-daemon

# Runtime Stage
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]